#' Plot coefficients
#'
#' @param df data frame generated by broom::tidy.lm
#'
#' @return ggplot2 object
#' @export
#'
#' @examples
#' NULL
plot_coef <- function(df) {
  ggplot(df, aes(continent, estimate, color = continent)) +
    geom_violin() +
    geom_point(position = position_jitter(width=0.3)) +
    facet_wrap(~term) +
    theme_bw()
}
